# Generated by Django 2.1.7 on 2019-02-15 12:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='person',
            name='mobile',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
