# Generated by Django 2.1.7 on 2019-02-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='doc',
            field=models.ImageField(upload_to='documents/'),
        ),
    ]
