# Generated by Django 2.1.7 on 2019-02-16 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp', '0002_auto_20190217_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='isp',
            name='desc',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='isp',
            name='maxSpeed',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='isp',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
